title: Build a LEGO Game Controller
hero_image: images/banner.png
description: lego-game-controller description
version: 4
listed: false
copyedit: false
last_tested: "2020-10-08"
steps:
  - title: Introduction
  - title: Motor encoders
  - title: The legendary game of Pong
  - title: Keepimg the ball in play
  - title: Adding paddles
  - title: Collisions
  - title: Finishing touches
  - title: What next
  
