---
title: Игровой контроллер LEGO®
hero_image: images/banner.png
description: Создание игрового контроллера с использованием LEGO® и Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-08"
steps:
  - 
    title: Введение
  - 
    title: Использование двигателей энкодеров LEGO® Spike™
  - 
    title: Реагирование на движение двигателя энкодера
  - 
    title: Делаем экран Понга
  - 
    title: Перемещаем мяч
  - 
    title: Управляем ракеткой
  - 
    title: Столкновение с ракеткой
  - 
    title: Улучшение своего проекта
  - 
    title: Что дальше?
