---
title: LEGO®ゲームコントローラー
hero_image: images/banner.png
description: Create a game controller using LEGO® and the Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-08"
steps:
  - 
    title: はじめに
  - 
    title: LEGO® Spike™ モーターエンコーダーを使う
  - 
    title: React to motor encoder movement
  - 
    title: Pongの画面を作る
  - 
    title: ボールを動かす
  - 
    title: パドルを制御する
  - 
    title: パドルの衝突
  - 
    title: 作品を改善する
  - 
    title: What next?
