---
title: LEGO® game controller
hero_image: images/banner.png
description: Create a game controller using LEGO® and the Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-08"
steps:
  - 
    title: Introduction
  - 
    title: Using LEGO® Spike™ motor encoders
  - 
    title: Reacting to motor encoder movement
  - 
    title: Making your Pong screen
  - 
    title: Moving the ball
  - 
    title: Control the paddle
  - 
    title: Paddle collisions
  - 
    title: Finishing touches
  - 
    title: What next
