---
title: Controlador de juego LEGO®
hero_image: images/banner.png
description: Crea un mando de juego utilizando LEGO® y Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-08"
steps:
  - title: Introducción
  - title: Utilización de los codificadores de motor LEGO® Spike ™
  - title: Reacción al movimiento del codificador del motor
  - title: Haciendo tu pantalla Pong
  - title: Moviendo la pelota
  - title: Controlando la paleta
  - title: Colisiones con la paleta
  - title: Mejora tu proyecto
  - title: '¿Qué hacer a continuación?'
