---
title: LEGO® Spielsteuerung
hero_image: images/banner.png
description: Erstelle einen Gamecontroller mit LEGO® und dem Build HAT
version: 4
listed: true
copyedit: true
last_tested: "2020-10-08"
steps:
  - 
    title: Einleitung
  - 
    title: Use LEGO® Spike™ motor encoders
  - 
    title: React to motor encoder movement
  - 
    title: Make your Pong screen
  - 
    title: Move the ball
  - 
    title: Steuere den Schläger
  - 
    title: Schlägerberührungen
  - 
    title: Improve your project
  - 
    title: What next?
