---
title: LEGO® 게임 컨트롤러
hero_image: images/banner.png
description: LEGO®와 Build HAT로 게임 컨트롤러를 만드세요
version: 4
listed: true
copyedit: true
last_tested: "2020-10-08"
steps:
  - 
    title: 들어가며
  - 
    title: Use LEGO® Spike™ motor encoders
  - 
    title: React to motor encoder movement
  - 
    title: Make your Pong screen
  - 
    title: Move the ball
  - 
    title: 패들 제어하기
  - 
    title: 패들 충돌
  - 
    title: Improve your project
  - 
    title: What next?
